version: '3'
#version 3

services:
  # Django
  app:
    build: .
    restart: unless-stopped
    container_name: BackEndApp
    command: /bin/bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --workers 4"
    volumes:
      - .:/app
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks:
      - net

  # Nginx
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/nginx/default.template:/etc/nginx/conf.d/default.conf.template
      - /etc/letsencrypt:/etc/letsencrypt
      - static_volume:/code/static
      - media_volume:/code/media
    command: bash -c "envsubst '$${HOST}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file:
      - .env
    environment:
      - HOST=${HOST}
    depends_on:
      - app
    networks:
      - net

volumes:
  static_volume:
  media_volume:


networks:
  net:
    driver: bridge